/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.53
 * Generated at: 2021-09-23 19:04:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class deletepassenger_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Delete Account</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/delete.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/footer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/header.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div>\r\n");
      out.write("		<!--NAVIGATION BAR-->\r\n");
      out.write("		<nav>\r\n");
      out.write("			<input type=\"checkbox\" id=\"check\"> <label for=\"check\"\r\n");
      out.write("				class=\"checkbtn\"> <i class=\"fas fa-bars\"></i>\r\n");
      out.write("			</label> <a class=\"log\" href=\"home.jsp\"><img id=\"logo\" src=\"IMG/logo.jpg\"\r\n");
      out.write("				alt=\"logo\" style=\"height: 200px;\"></a>\r\n");
      out.write("\r\n");
      out.write("			<ul class=\"nav-ul\">\r\n");
      out.write("				<li><a id=\"nav\" href=\"home.jsp\">Home</a></li>\r\n");
      out.write("				<li><a id=\"nav\" href=\"#\">About Us</a></li>\r\n");
      out.write("				<li><a id=\"nav\" href=\"#\">Contact Us</a></li>\r\n");
      out.write("				<li><a id=\"nav\" href=\"#\">Booking</a></li>\r\n");
      out.write("				<li><a id=\"nav\" href=\"#\">Schedules</a></li>\r\n");
      out.write("				<li><a id=\"nav\" href=\"#\">Search</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("		</nav>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div>\r\n");
      out.write("\r\n");
      out.write("		");

		String username = request.getParameter("username");
		String fname = request.getParameter("fname");
		String lname = request.getParameter("lname");
		String email = request.getParameter("email");
		String dob = request.getParameter("dob");
		String gender = request.getParameter("gender");
		String phone = request.getParameter("phone");
		String nic = request.getParameter("nic");
		String address = request.getParameter("address");
		String password = request.getParameter("password");
		
      out.write("\r\n");
      out.write("		<div>\r\n");
      out.write("			<form action=\"delete\" method=\"POST\">\r\n");
      out.write("				<center>\r\n");
      out.write("					<br> <br>\r\n");
      out.write("\r\n");
      out.write("					<fieldset id=\"del\" style=\"border-radius: 50px;\">\r\n");
      out.write("						<br>\r\n");
      out.write("\r\n");
      out.write("						<h1>Delete Profile</h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<br> <br>\r\n");
      out.write("						<p style=\"margin-left: 02px;\">\r\n");
      out.write("							Username : <input type=\"text\" name=\"username\"\r\n");
      out.write("								value=\"");
      out.print(username);
      out.write("\" readonly\r\n");
      out.write("								style=\"padding-left: 20px; margin-left: 20px; width: 150px\">\r\n");
      out.write("						</p>\r\n");
      out.write("						<br>\r\n");
      out.write("						<p style=\"margin-left: -01px;\">\r\n");
      out.write("							First Name : <input type=\"text\" name=\"fname\" value=\"");
      out.print(fname);
      out.write("\"\r\n");
      out.write("								readonly\r\n");
      out.write("								style=\"padding-left: 20px; margin-left: 20px; width: 150px\">\r\n");
      out.write("						</p>\r\n");
      out.write("						<br>\r\n");
      out.write("						<p>\r\n");
      out.write("							Last Name : <input type=\"text\" name=\"lname\" value=\"");
      out.print(lname);
      out.write("\"\r\n");
      out.write("								readonly\r\n");
      out.write("								style=\"padding-left: 20px; margin-left: 20px; width: 150px\">\r\n");
      out.write("						</p>\r\n");
      out.write("						<br>\r\n");
      out.write("						<p style=\"margin-left: 87px;\">\r\n");
      out.write("							Email : <input type=\"email\" name=\"email\" value=\"");
      out.print(email);
      out.write("\"\r\n");
      out.write("								readonly\r\n");
      out.write("								style=\"padding-left: 20px; margin-left: 20px; width: 200px\">\r\n");
      out.write("						</p>\r\n");
      out.write("						<br>\r\n");
      out.write("						<p style=\"margin-left: 05px;\">\r\n");
      out.write("							Date Of Birth : <input type=\"date\" name=\"dob\" value=\"");
      out.print(dob);
      out.write("\"\r\n");
      out.write("								readonly\r\n");
      out.write("								style=\"padding-left: 20px; margin-left: 20px; width: 175px\">\r\n");
      out.write("						</p>\r\n");
      out.write("						<br>\r\n");
      out.write("						<p style=\"margin-left: 30px;\">\r\n");
      out.write("							Gender :<input type=\"text\" name=\"gender\" value=\"");
      out.print(gender);
      out.write("\"\r\n");
      out.write("								style=\"padding-left: 20px; margin-left: 20px; width: 150px\">\r\n");
      out.write("						</p>\r\n");
      out.write("						<br>\r\n");
      out.write("						<p style=\"margin-right: 60px;\">\r\n");
      out.write("							Telephone Number : <input type=\"text\" name=\"phone\"\r\n");
      out.write("								value=\"");
      out.print(phone);
      out.write("\" readonly\r\n");
      out.write("								style=\"padding-left: 20px; margin-left: 20px; width: 150px\">\r\n");
      out.write("						</p>\r\n");
      out.write("						<br>\r\n");
      out.write("						<p style=\"margin-left: -12px;\">\r\n");
      out.write("							NIC Number : <input type=\"text\" name=\"nic\" value=\"");
      out.print(nic);
      out.write("\"\r\n");
      out.write("								readonly\r\n");
      out.write("								style=\"padding-left: 20px; margin-left: 20px; width: 150px\">\r\n");
      out.write("						</p>\r\n");
      out.write("						<br>\r\n");
      out.write("						<p style=\"margin-left: 68px;\">\r\n");
      out.write("							Address : <input type=\"text\" name=\"address\" value=\"");
      out.print(address);
      out.write("\"\r\n");
      out.write("								readonly\r\n");
      out.write("								style=\"padding-left: 20px; margin-left: 20px; width: 200px\">\r\n");
      out.write("						</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						</p>\r\n");
      out.write("						<br> <br> <br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<center>\r\n");
      out.write("							<button type=\"submit\" id=\"submit\" name=\"submit\" class=\"delACTG\">Delete\r\n");
      out.write("								Profile</button>\r\n");
      out.write("							<br> <br>\r\n");
      out.write("						</center>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br>\r\n");
      out.write("		</fieldset>\r\n");
      out.write("		</center>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<div id=\"footer1\">\r\n");
      out.write("		<!--  <p><span id=\"supe1\">SUPERNIC AUDIO</span></p> -->\r\n");
      out.write("		<p class=\"add\">\r\n");
      out.write("			<span class=\"sp\">Our Services</span><br /> <br /> <a class=\"foot\"\r\n");
      out.write("				href=\"#\">Train Booking</a><br /> <a class=\"foot\" href=\"#\">Lodging</a><br />\r\n");
      out.write("			<a class=\"foot\" href=\"#\">Accommodation</a> <br> <a class=\"foot\"\r\n");
      out.write("				href=\"#\">Courier Services</a><br> <a class=\"foot\" href=\"#\">Freight\r\n");
      out.write("				Transportation</a><br>\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("		<p class=\"add\">\r\n");
      out.write("			<span class=\"sp\">Categories</span><br /> <br /> <a class=\"foot\"\r\n");
      out.write("				href=\"#\">Booking</a><br /> <a class=\"foot\"\r\n");
      out.write("				href=\"passengerinsert.jsp\">Registration</a><br /> <a class=\"foot\"\r\n");
      out.write("				href=\"login.jsp\">Login</a><br /> <a class=\"foot\" href=\"#\">Inquiries</a><br />\r\n");
      out.write("			<a class=\"foot\" href=\"#\">Schedules</a>\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("		<p class=\"add\">\r\n");
      out.write("			<span class=\"sp\">Metro Railways</span><br /> <br /> <a class=\"foot\"\r\n");
      out.write("				href=\"#\">About Us</a> <br> <a class=\"foot\" href=\"#\">Explore</a><br />\r\n");
      out.write("			<a class=\"foot\" href=\"#\">Contact Us</a><br /> <a class=\"foot\"\r\n");
      out.write("				href=\"#\">Security and Safety</a> <br /> <a class=\"foot\" href=\"#\">Privacy\r\n");
      out.write("				Policy</a>\r\n");
      out.write("		</p>\r\n");
      out.write("		<!--  <p class=\"a\"><span class=\"flo\" >FOLLOW US</span> </p><br/>-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"f-logo\">\r\n");
      out.write("			<br> <a href=\"home.jsp\"> <img id=\"f-logo\" src=\"IMG/logo.jpg\"\r\n");
      out.write("				alt=\"f_logo\" style=\"height: 200px;\"></a>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
