/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.53
 * Generated at: 2021-10-03 17:40:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/home.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/footer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/headerhome.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"black\">\r\n");
      out.write("	<div>\r\n");
      out.write("		<!--NAVIGATION BAR-->\r\n");
      out.write("		<nav>\r\n");
      out.write("			<input type=\"checkbox\" id=\"check\"> <label for=\"check\"\r\n");
      out.write("				class=\"checkbtn\"> <i class=\"fas fa-bars\"></i>\r\n");
      out.write("			</label>\r\n");
      out.write("			<div class=\"btn \">\r\n");
      out.write("				<a href=\"passengerinsert.jsp\"><button class=\"button1\"\r\n");
      out.write("						name=\"btn1 \">\r\n");
      out.write("						<b>Register</b>\r\n");
      out.write("					</button></a> <a href=\"login.jsp\"><button class=\"button1\" name=\"btn1 \">\r\n");
      out.write("						<b>Login</b>\r\n");
      out.write("					</button></a>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<a class=\"log\" href=\"#\"><img id=\"logo\" src=\"IMG/logo.jpg\"\r\n");
      out.write("				style=\"height: 200px;\"logo\"></a>\r\n");
      out.write("\r\n");
      out.write("			<ul class=\"nav-ul\">\r\n");
      out.write("				<li><a id=\"nav\" href=\"#\">Home</a></li>\r\n");
      out.write("				<li><a id=\"nav\" href=\"#\">About Us</a></li>\r\n");
      out.write("				<li><a id=\"nav\" href=\"#\">Contact Us</a></li>\r\n");
      out.write("				<li><a id=\"nav\" href=\"#\">Booking</a></li>\r\n");
      out.write("				<li><a id=\"nav\" href=\"#\">Schedules</a></li>\r\n");
      out.write("				<li><a id=\"nav\" href=\"#\">Search</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("		</nav>\r\n");
      out.write("		<br>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"slider\">\r\n");
      out.write("			<div class=\"slideshow-container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"mySlides fade\">\r\n");
      out.write("\r\n");
      out.write("					<img src=\"IMG/railway.jpg\" style=\"width: 100%; height: 600px;\">\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"mySlides fade\">\r\n");
      out.write("\r\n");
      out.write("					<img src=\"IMG/sri-lanka.jpg\" style=\"width: 100%; height: 600px;\">\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mySlides fade\">\r\n");
      out.write("\r\n");
      out.write("					<img src=\"IMG/badulla.jpg\" style=\"width: 100%; height: 600px;\">\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"dots\" style=\"margin-right: 915px;\">\r\n");
      out.write("				<span class=\"dot\"></span> <span class=\"dot\"></span> <span\r\n");
      out.write("					class=\"dot\"></span>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<script>\r\n");
      out.write("				var slideIndex = 0;\r\n");
      out.write("				showSlides();\r\n");
      out.write("\r\n");
      out.write("				function showSlides() {\r\n");
      out.write("					var i;\r\n");
      out.write("					var slides = document.getElementsByClassName(\"mySlides\");\r\n");
      out.write("					var dots = document.getElementsByClassName(\"dot\");\r\n");
      out.write("					for (i = 0; i < slides.length; i++) {\r\n");
      out.write("						slides[i].style.display = \"none\";\r\n");
      out.write("					}\r\n");
      out.write("					slideIndex++;\r\n");
      out.write("					if (slideIndex > slides.length) {\r\n");
      out.write("						slideIndex = 1\r\n");
      out.write("					}\r\n");
      out.write("					for (i = 0; i < dots.length; i++) {\r\n");
      out.write("						dots[i].className = dots[i].className.replace(\r\n");
      out.write("								\" active\", \"\");\r\n");
      out.write("					}\r\n");
      out.write("					slides[slideIndex - 1].style.display = \"block\";\r\n");
      out.write("					dots[slideIndex - 1].className += \" active\";\r\n");
      out.write("					setTimeout(showSlides, 2000); // Change image every 2 seconds\r\n");
      out.write("				}\r\n");
      out.write("			</script>\r\n");
      out.write("\r\n");
      out.write("			<!--cat-->\r\n");
      out.write("			<br>\r\n");
      out.write("			<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--second css-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"expr\" style=\"margin-left: 275px;\">\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"experiences\">\r\n");
      out.write("			<div class=\"box\">\r\n");
      out.write("				<div class=\"img1\">\r\n");
      out.write("					<img src=\"IMG/nine.jpg\" alter=\"picture\" height=\"380px\"\r\n");
      out.write("						width=\"350px\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<!--<div class=\"overlay\"></div>-->\r\n");
      out.write("				<div class=\"overlay2\"></div>\r\n");
      out.write("				<div class=\"text\">\r\n");
      out.write("\r\n");
      out.write("					<h2>Ella</h2>\r\n");
      out.write("					<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<p>Ella train journey is said to be one of the most scenic,\r\n");
      out.write("						epic train journeys in not only just Sri Lanka but the world. So\r\n");
      out.write("						with a few days to spare in Sri Lanka.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"box\">\r\n");
      out.write("				<div class=\"img2\">\r\n");
      out.write("					<img src=\"IMG/train.jpg\" alter=\"picture\" height=\"380\" width=\"350px\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"overlay2\"></div>\r\n");
      out.write("				<div class=\"text\">\r\n");
      out.write("\r\n");
      out.write("					<h2>Badulla</h2>\r\n");
      out.write("					<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<p>Badulla is located in the southeast of Kandy, almost\r\n");
      out.write("						encircled by the Badulu Oya River, about 680 m (2,230 ft) above\r\n");
      out.write("						sea level and is surrounded by tea plantations.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"box\">\r\n");
      out.write("				<div class=\"img3\">\r\n");
      out.write("					<img src=\"IMG/jaffna.jpg\" alter=\"picture\" height=\"380\"\r\n");
      out.write("						width=\"350px\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"overlay2\"></div>\r\n");
      out.write("				<div class=\"text\">\r\n");
      out.write("\r\n");
      out.write("					<h2>Jaffna</h2>\r\n");
      out.write("					<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<p>Jaffna is a city on the northern tip of Sri Lanka. Nallur\r\n");
      out.write("						Kandaswamy is a huge Hindu temple with golden arches and an ornate\r\n");
      out.write("						gopuram tower. By the coast, star-shaped Jaffna Fort was built by\r\n");
      out.write("						the Portuguese in the 17th century and later occupied by the Dutch\r\n");
      out.write("						and British.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("		<br>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"experiences\">\r\n");
      out.write("			<div class=\"box\">\r\n");
      out.write("				<div class=\"img1\">\r\n");
      out.write("					<img src=\"IMG/haputale.jpg\" alter=\"picture\" height=\"380\"\r\n");
      out.write("						width=\"350px\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"overlay2\"></div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"text\">\r\n");
      out.write("\r\n");
      out.write("					<h2>Haputale</h2>\r\n");
      out.write("					<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<p>Haputale Railway Station is the 69th station on the Main\r\n");
      out.write("						Line. The station is located between Idalgashinna and Diyatalawa\r\n");
      out.write("						railway stations in Badulla District, Uva Province.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"box\">\r\n");
      out.write("				<div class=\"img2\">\r\n");
      out.write("					<img src=\"IMG/untitled.jpg\" alter=\"picture\" height=\"380\"\r\n");
      out.write("						width=\"350px\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"overlay2\"></div>\r\n");
      out.write("				<div class=\"text\">\r\n");
      out.write("\r\n");
      out.write("					<h2>Kandy</h2>\r\n");
      out.write("					<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<p>The Kandy to Ella train actually starts in Colombo, but the\r\n");
      out.write("						highlights are the journey from Kandy to Ella and takes about 9-10\r\n");
      out.write("						hours in total (the timetables will try to tell you that it is a 6\r\n");
      out.write("						hour journey!). It stops at Hill Country towns like Nuwara Eliya\r\n");
      out.write("						and Haputale, places we highly recommend visiting.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"box\">\r\n");
      out.write("				<div class=\"img3\">\r\n");
      out.write("					<img src=\"IMG/fort.jpg\" alter=\"picture\" height=\"380\" width=\"350px\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"overlay2\"></div>\r\n");
      out.write("				<div class=\"text\">\r\n");
      out.write("\r\n");
      out.write("					<h2>Colombo Fort</h2>\r\n");
      out.write("					<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<p>Fort railway station is a major rail hub in Colombo, Sri\r\n");
      out.write("						Lanka. The station is served by Sri Lanka Railways, with many\r\n");
      out.write("						inter-city and commuter trains entering each day. Fort Station is\r\n");
      out.write("						the main rail gateway to central Colombo; it is the terminus of\r\n");
      out.write("						most intercity trains in the country.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<div id=\"footer1\">\r\n");
      out.write("		<!--  <p><span id=\"supe1\">SUPERNIC AUDIO</span></p> -->\r\n");
      out.write("		<p class=\"add\">\r\n");
      out.write("			<span class=\"sp\">Our Services</span><br />\r\n");
      out.write("			<br />\r\n");
      out.write("			<a class=\"foot\" href=\"#\">Train Booking</a><br />\r\n");
      out.write("			<a class=\"foot\" href=\"#\">Lodging</a><br />\r\n");
      out.write("			<a class=\"foot\" href=\"#\">Accommodation</a> <br>\r\n");
      out.write("			<a class=\"foot\" href=\"#\">Courier Services</a><br>\r\n");
      out.write("			<a class=\"foot\" href=\"#\">Freight Transportation</a><br>\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("		<p class=\"add\">\r\n");
      out.write("			<span class=\"sp\">Categories</span><br />\r\n");
      out.write("			<br />\r\n");
      out.write("			<a class=\"foot\" href=\"#\">Booking</a><br />\r\n");
      out.write("			<a class=\"foot\" href=\"#\">Inquiries</a><br />\r\n");
      out.write("			<a class=\"foot\" href=\"#\">Schedules</a>\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("		<p class=\"add\">\r\n");
      out.write("			<span class=\"sp\">Metro Railways</span><br />\r\n");
      out.write("			<br />\r\n");
      out.write("			<a class=\"foot\" href=\"#\">About Us</a> <br>\r\n");
      out.write("			<a class=\"foot\" href=\"#\">Explore</a><br />\r\n");
      out.write("			<a class=\"foot\" href=\"#\">Contact Us</a><br />\r\n");
      out.write("			<a class=\"foot\" href=\"#\">Security and Safety</a> <br />\r\n");
      out.write("			<a class=\"foot\" href=\"#\">Privacy Policy</a>\r\n");
      out.write("		</p>\r\n");
      out.write("		<!--  <p class=\"a\"><span class=\"flo\" >FOLLOW US</span> </p><br/>-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"f-logo\">\r\n");
      out.write("			<br> <a href=\"#\"> <img id=\"f-logo\" src=\"IMG/logo.jpg\"\r\n");
      out.write("				alt=\"f_logo\" style=\"height: 200px;\"></a>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
