/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.53
 * Generated at: 2021-09-23 20:09:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class passengerinsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Create Account</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/insert.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/footer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/headerinsert.css\">\r\n");
      out.write("<script src=\"JS/myscript.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".blink {\r\n");
      out.write("  animation: blink 2s infinite;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes blink {\r\n");
      out.write("  0% {\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("  }\r\n");
      out.write("  50% {\r\n");
      out.write("    opacity: 0;\r\n");
      out.write("  }\r\n");
      out.write("  100% {\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!--NAVIGATION BAR-->\r\n");
      out.write("	<nav>\r\n");
      out.write("		<input type=\"checkbox\" id=\"check\"> <label for=\"check\"\r\n");
      out.write("			class=\"checkbtn\"> <i class=\"fas fa-bars\"></i>\r\n");
      out.write("		</label>\r\n");
      out.write("		<div class=\"btn \">\r\n");
      out.write("			<a href=\"login.jsp\"><button class=\"button1\" name=\"btn1 \">\r\n");
      out.write("					<b>Login</b>\r\n");
      out.write("				</button></a>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<a class=\"log\" href=\"home.jsp\"><img id=\"logo\" src=\"IMG/logo.jpg\"\r\n");
      out.write("			style=\"height: 200px;\"logo\"></a>\r\n");
      out.write("\r\n");
      out.write("		<ul class=\"nav-ul\">\r\n");
      out.write("			<li><a id=\"nav\" href=\"home.jsp\">Home</a></li>\r\n");
      out.write("			<li><a id=\"nav\" href=\"#\">About Us</a></li>\r\n");
      out.write("			<li><a id=\"nav\" href=\"#\">Contact Us</a></li>\r\n");
      out.write("			<li><a id=\"nav\" href=\"#\">Booking</a></li>\r\n");
      out.write("			<li><a id=\"nav\" href=\"#\">Schedules</a></li>\r\n");
      out.write("			<li><a id=\"nav\" href=\"#\">Search</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("\r\n");
      out.write("	</nav>\r\n");
      out.write("	<br>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"content\" id=\"content\">\r\n");
      out.write("		<form action=\"insert\" method=\"POST\">\r\n");
      out.write("			<center>\r\n");
      out.write("				<br>\r\n");
      out.write("				<fieldset class=\"CAcont\" style=\"border-radius: 50px;\">\r\n");
      out.write("\r\n");
      out.write("					<br> <br>\r\n");
      out.write("					<h1>Create Profile</h1>\r\n");
      out.write("					<br> <br>\r\n");
      out.write("\r\n");
      out.write("					<p style=\"margin-left: -45px;\">\r\n");
      out.write("						Create Username : <input type=\"text\" name=\"username\"\r\n");
      out.write("							style=\"border-radius: 10px; padding-right: 75px; margin-left: 3px;\"\r\n");
      out.write("							id=\"userName\" required>\r\n");
      out.write("					</p>\r\n");
      out.write("					<br>\r\n");
      out.write("\r\n");
      out.write("					<p style=\"margin-left: 2px;\">\r\n");
      out.write("						First Name : <input type=\"text\" name=\"fname\"\r\n");
      out.write("							style=\"border-radius: 10px; padding-right: 75px; margin-left: 3px;\"\r\n");
      out.write("							id=\"firstName\" required>\r\n");
      out.write("					</p>\r\n");
      out.write("					<br>\r\n");
      out.write("\r\n");
      out.write("					<p style=\"margin-left: 5px;\">\r\n");
      out.write("						Last Name : <input type=\"text\" name=\"lname\"\r\n");
      out.write("							style=\"border-radius: 10px; padding-right: 75px; margin-left: 3px;\"\r\n");
      out.write("							required>\r\n");
      out.write("					</p>\r\n");
      out.write("					<br>\r\n");
      out.write("\r\n");
      out.write("					<p style=\"margin-left: 0px;\">\r\n");
      out.write("						Email &emsp; : <input type=\"email\" name=\"email\"\r\n");
      out.write("							style=\"border-radius: 10px; width: 250px; height: 25px; margin-left: 3px;\"\r\n");
      out.write("							required placeholder=\"example@anywhere.com\"\r\n");
      out.write("							pattern=\"[a-z0-9._%+_-]+@[a-z0-9._]+\\.[a-z]{2,3}\">\r\n");
      out.write("					</p>\r\n");
      out.write("					<br>\r\n");
      out.write("\r\n");
      out.write("					<p style=\"margin-right: 40px;\">\r\n");
      out.write("						Date of Birth &emsp;: <input type=\"date\" id=\"dob\" name=\"dob\"\r\n");
      out.write("							style=\"padding-inline: 50px; border-radius: 10px; margin-left: 3px;\"\r\n");
      out.write("							required>\r\n");
      out.write("					</p>\r\n");
      out.write("					<br>\r\n");
      out.write("\r\n");
      out.write("					<p style=\"margin-right: 150px;\">\r\n");
      out.write("						Select Gender : &emsp; <select name=\"gender\"\r\n");
      out.write("							style=\"padding-right: 75px; border-radius: 10px; margin-left: -17px;\">\r\n");
      out.write("\r\n");
      out.write("							<option value=\"Male\">Male</option>\r\n");
      out.write("							<option value=\"Female\">Female</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</p>\r\n");
      out.write("					<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<p style=\"margin-left: -55px;\">\r\n");
      out.write("						Telephone Number : <input type=\"text\" name=\"phone\"\r\n");
      out.write("							style=\"border-radius: 10px; padding-right: 75px; margin-left: 3px;\"\r\n");
      out.write("							required>\r\n");
      out.write("					</p>\r\n");
      out.write("					<br>\r\n");
      out.write("\r\n");
      out.write("					<p style=\"margin-left: -4px;\">\r\n");
      out.write("						NIC Number : <input type=\"text\" name=\"nic\"\r\n");
      out.write("							style=\"border-radius: 10px; padding-right: 75px; margin-left: 4;\"\r\n");
      out.write("							required required>\r\n");
      out.write("					</p>\r\n");
      out.write("					<br> <br>\r\n");
      out.write("					<h3 style=\"color: red\" class=\"blink\">\r\n");
      out.write("						WARNING : Once the National Identity Card Number is entered and\r\n");
      out.write("						Account is created <br> IT CANNOT BE CHANGED AGAIN !!\r\n");
      out.write("					</h3>\r\n");
      out.write("					<br> <br>\r\n");
      out.write("					<p style=\"margin-left: 23px;\">\r\n");
      out.write("						Address : <input type=\"text\" name=\"address\"\r\n");
      out.write("							style=\"border-radius: 10px; padding-right: 75px; margin-left: 3px;\"\r\n");
      out.write("							required required>\r\n");
      out.write("					</p>\r\n");
      out.write("					<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<p style=\"margin-left: -40px;\">\r\n");
      out.write("						Create Password : <input type=\"password\" name=\"createPW\"\r\n");
      out.write("							id=\"epassword\"\r\n");
      out.write("							style=\"border-radius: 10px; padding-right: 75px; margin-left: 3;\"\r\n");
      out.write("							required required>\r\n");
      out.write("					</p>\r\n");
      out.write("					<br>\r\n");
      out.write("\r\n");
      out.write("					<p style=\"margin-right: 53px;\">\r\n");
      out.write("						Confirm Password : <input type=\"password\" id=\"repassword\"\r\n");
      out.write("							name=\"confirmPW\"\r\n");
      out.write("							style=\"border-radius: 10px; padding-right: 75px; margin-left: 3px;\"\r\n");
      out.write("							required>\r\n");
      out.write("					</p>\r\n");
      out.write("					<br> <br>\r\n");
      out.write("\r\n");
      out.write("					<center>\r\n");
      out.write("						&emsp13;\r\n");
      out.write("						<button id=\"submit\" type=\"submit\" class=\"CAbtn\"\r\n");
      out.write("							onmouseover=\"checkpasswords()\" name=\"submit\">Create\r\n");
      out.write("							Account</button>\r\n");
      out.write("						&emsp14;\r\n");
      out.write("						<button type=\"reset\" class=\"CAbtn\">Reset</button>\r\n");
      out.write("						<br> <br>\r\n");
      out.write("					</center>\r\n");
      out.write("	</div>\r\n");
      out.write("	</fieldset>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	</center>\r\n");
      out.write("	</form>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"footer1\">\r\n");
      out.write("		<!--  <p><span id=\"supe1\">SUPERNIC AUDIO</span></p> -->\r\n");
      out.write("		<p class=\"add\">\r\n");
      out.write("			<span class=\"sp\">Our Services</span><br /> <br /> <a class=\"foot\"\r\n");
      out.write("				href=\"#\">Train Booking</a><br /> <a class=\"foot\" href=\"#\">Lodging</a><br />\r\n");
      out.write("			<a class=\"foot\" href=\"#\">Accommodation</a> <br> <a class=\"foot\"\r\n");
      out.write("				href=\"#\">Courier Services</a><br> <a class=\"foot\" href=\"#\">Freight\r\n");
      out.write("				Transportation</a><br>\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("		<p class=\"add\">\r\n");
      out.write("			<span class=\"sp\">Categories</span><br /> <br /> <a class=\"foot\"\r\n");
      out.write("				href=\"#\">Booking</a><br /> <a class=\"foot\"\r\n");
      out.write("				href=\"passengerinsert.jsp\">Registration</a><br /> <a class=\"foot\"\r\n");
      out.write("				href=\"login.jsp\">Login</a><br /> <a class=\"foot\" href=\"#\">Inquiries</a><br />\r\n");
      out.write("			<a class=\"foot\" href=\"#\">Schedules</a>\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("		<p class=\"add\">\r\n");
      out.write("			<span class=\"sp\">Metro Railways</span><br /> <br /> <a class=\"foot\"\r\n");
      out.write("				href=\"#\">About Us</a> <br> <a class=\"foot\" href=\"#\">Explore</a><br />\r\n");
      out.write("			<a class=\"foot\" href=\"#\">Contact Us</a><br /> <a class=\"foot\"\r\n");
      out.write("				href=\"#\">Security and Safety</a> <br /> <a class=\"foot\" href=\"#\">Privacy\r\n");
      out.write("				Policy</a>\r\n");
      out.write("		</p>\r\n");
      out.write("		<!--  <p class=\"a\"><span class=\"flo\" >FOLLOW US</span> </p><br/>-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"f-logo\">\r\n");
      out.write("			<br> <a href=\"home.jsp\"> <img id=\"f-logo\" src=\"IMG/logo.jpg\"\r\n");
      out.write("				alt=\"f_logo\" style=\"height: 200px;\"></a>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
